### ISSUE TITLE
File Names

### ISSUE THREAD

**Issue by andy29485** [DHS-Computer-Science/DHS-HSPC#1]
@noahdavis319 
So I looked at 54e8976, and I was saw a possible conflict between our parts of the project(I may be wrong).

So the Grader watches for submissions, [moves them to a temp directory](https://github.com/DHS-Computer-Science/DHS-HSPC/blob/54e8976e8ac4c7f410af8d0917009069c5127448/Grading_Program/SubmissionWatcher.py#L14)(awaiting to be graded), then when it's done grading it moves them to a completed directory. **So there will be almost no files in the submission dir.**

From what I understand, the Submitter is checking if a file already exists. 

Proposed solutions:
1) My grader will leave files where they are.
- Should not be a problem since Grader watches for file creation(not reading a directory), so old assignments _should_ not be added to grading queue.
- I'm not entirely done implementing the process that I have described, so changing will not be problematic.

2) Submitter checks MySQL db for used filenames.

**Comment by noahdavis319** [comment]
Which solution does the grading program currently use? Checking if the
filename is already in use is an extremely easy change.

Which would you prefer?

**Comment by andy29485** [comment]
Both are fine, I just need to know which you think will be more stable.

**Comment by andy29485** [comment]
Interesting.

**Comment by noahdavis319** [comment]
Let's do it how you were planning on doing it (multiple directories,
submission folder just about always empty).

**Comment by andy29485** [comment]
Ok, then.
